/*************************************************************************** 
 *                                                                         *
 *    File:         copy.hpp                                               *
 *                                                                         *
 *    Description:  This file contains the function prototypes and data    *
 *                  structures used within the copy.HPP file.              *
 *                                                                         *
 *    Copyright:                                                           *
 *    Date:         01 Jan 1997                                            *
 *                                                                         *
 *    Note:         Generated by the Guidelines code generation facility.  *
 *                                                                         *
 ***************************************************************************/

#ifndef HPP_COPY
#define HPP_COPY


/*************************************************************************** 
 *    Include files.                                                       *
 ***************************************************************************/


/*************************************************************************** 
 *    Window/control identifiers.                                          *
 ***************************************************************************/

#define IDD_DUPLICATE        3000                /* Dialog                 */
#define IDD_DI_DRV           3001                /* Entry Field            */
#define IDD_DI_T2            3002                /* Combobox               */
#define IDD_DI_T3            3003                /* Combobox               */
#define IDD_DI_OK            3004                /* Push Button            */
#define IDD_DI_CANCEL        3005                /* Push Button            */
#define IDD_IMAGEDIALOG      3006                /* Dialog                 */
#define IDD_STATIC1          3007                /* Static Text            */
#define IDD_STATIC2          3008                /* Static Text            */
#define IDD_STATIC3          3009                /* Static Text            */
#define IDD_STATIC4          3010                /* Static Text            */
#define IDD_PBSTART          3011                /* Push Button            */
#define IDD_PBCANCEL         3012                /* Push Button            */
#define IDD_EF_DISKFILE      3013                /* Combobox               */
#define IDD_CBIMAGE1         3014                /* Combobox               */
#define IDD_CBIMAGE2         3015                /* Combobox               */


/*************************************************************************** 
 *    Global variables.                                                    *
 ***************************************************************************/

#ifndef RC_INVOKED
extern WINDOW  wDuplicate;
extern WINDOW  wImageDialog;
#endif /* !RC_INVOKED */


/*************************************************************************** 
 *    Function Prototypes.                                                 *
 ***************************************************************************/

#ifndef RC_INVOKED
PMENTRY DuplicateWndProc (HWND hwnd, ULONG msg, MPARAM mp1, MPARAM mp2);
PMENTRY ImageDialogWndProc (HWND hwnd, ULONG msg, MPARAM mp1, MPARAM mp2);
#endif /* !RC_INVOKED */



#endif /* HPP_COPY */

