/*
 *   This file was automatically generated by version 1.7 of C:\BINP\CEXTRACT.EXE.
 *   Manual editing not recommended.
 *
 *   Created: Thu Jan 20 18:01:49 1994
 */
#ifndef __CEXTRACT__

void GetImageList ( HWND hwnd, USHORT EditB, USHORT ListB );
USHORT SetBox ( HWND hwnd, MPARAM mp1 );
BOOL SetDrive ( HWND hwnd, USHORT curBuff );
MRESULT EXPENTRY ReadDlgProc ( HWND hwnd, ULONG id, MPARAM mp1, MPARAM mp2 );
MRESULT EXPENTRY WriteDlgProc ( HWND hwnd, ULONG id, MPARAM mp1, MPARAM mp2 );
MRESULT EXPENTRY DeleteDlgProc ( HWND hwnd, ULONG id, MPARAM mp1, MPARAM mp2 );
void GetDirList ( HWND hwnd, CHAR *pcCurrentPath );
void GetFileList ( HWND hwnd );
BOOL ParseFileName ( CHAR *pcOut, CHAR *pcIn );
BOOL CheckLSParms ( HWND hwnd, USHORT Mode );
MRESULT EXPENTRY LoadDlgProc ( HWND hwnd, ULONG id, MPARAM mp1, MPARAM mp2 );
MRESULT EXPENTRY SaveDlgProc ( HWND hwnd, ULONG id, MPARAM mp1, MPARAM mp2 );
USHORT SetEdit ( HWND hwnd, USHORT EditB );
MRESULT EXPENTRY CompDlgProc ( HWND hwnd, ULONG id, MPARAM mp1, MPARAM mp2 );
MRESULT EXPENTRY duplicateDlgProc(HWND hwnd, ULONG id, MPARAM mp1, MPARAM mp2);
MRESULT EXPENTRY copyCheckDlgProc(HWND hwnd, ULONG id, MPARAM mp1, MPARAM mp2);
MRESULT EXPENTRY AboutDlgProc ( HWND hwnd, ULONG id, MPARAM mp1, MPARAM mp2 );
MRESULT EXPENTRY floppyToFileDlgProc (HWND hwnd, ULONG id, MPARAM mp1, MPARAM mp2);
MRESULT EXPENTRY fileToFloppyDlgProc (HWND hwnd, ULONG id, MPARAM mp1, MPARAM mp2);
void APIENTRY readsource ( ULONG curTh );
SHORT fmttbl_bytessec ( USHORT bytesPerSec, USHORT *DiskError );
void APIENTRY writetarget ( ULONG curTh );
SHORT bspblkcmp ( BIOSPARAMETERBLOCK *blk1, BIOSPARAMETERBLOCK *blk2 );
void ThreadErrorHandler ( USHORT Msg, USHORT curTh, HFILE dHandle );
USHORT SetBufferSel ( USHORT curBuff );
static PBYTE MakeHugeP ( USHORT curBuff, USHORT Trk );
void APIENTRY LoadImage ( ULONG curTh );
void APIENTRY SaveImage ( ULONG curTh );
void APIENTRY CompImages ( ULONG curTh );
int main ( void );
MRESULT EXPENTRY ClientWndProc ( HWND hwnd, ULONG id, MPARAM mp1, MPARAM mp2 );
MRESULT Panic ( PCH pszCaption, USHORT ErrorNum );
MRESULT DisplayStatus ( HWND hwnd, HPS hPS, USHORT curTh );
MRESULT DisplayDone ( HWND hwnd, HPS hPS, USHORT curBuff );
void FreeThread ( USHORT curTh );
void DisplayImageStat ( HWND hwnd, HPS hPS );
void PutBox ( PSZ msg1, PSZ msg2 );
void freeImageBuffer (USHORT buffer);

#endif /* __CEXTRACT__ */
